---
title: "Politetico Divisivo"
author: "Erick Hernández"
date: "6/2/2020"
output: html_document
---

```{r eval=TRUE}
library(cluster)
library(purrr)
library(carData)##Llamar base de datos
data<-Freedman ###Renombrar base de datos
data<-na.omit(data) #Omitir NA´s
data <- scale(data) #Escalar variables numéricas
hc4 <- diana(data) ## Computo de agrupamientos jerárquicos divisivos
hc4$dc ##Coeficiente de división
pltree(hc4, cex = 0.6, hang = -1, main = "Dendrogram of diana") ###Dendograma( cada grupo está vinculado a dos o más grupos sucesores)###
clust <- cutree(hc4, k = 5)###Cortar el arbol en 5 grupos
library(factoextra)
fviz_cluster(list(data = data, cluster = clust))
pltree(hc4, hang=-1, cex = 0.6)
rect.hclust(hc4, k = 9, border = 2:10)
```

```{r}
datos15<-read.csv("ss_n_cs_n.csv",header = T)

datos_me<-subset(datos15, year==2060)

datos_me$experiment<-ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="abundancia",1,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="asentamientos",2,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="base",3,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="sequia",4,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="sin_extraccion",5,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="abundancia",6,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="asentamientos",7,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="base",8,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="sequia",9,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="sin_extraccion",10,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="abundancia",11,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="asentamientos",12,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="base",13,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="sequia",14,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="sin_extraccion",15,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="abundancia",16,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="asentamientos",17,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="base",18,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="sequia",19,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="sin_extraccion",20,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="abundancia",21,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="asentamientos",22,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="base",23,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="sequia",24,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="sin_extraccion",25,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="abundancia",26,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="asentamientos",27,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="base",28,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="sequia",29,30)))))))))))))))))))))))))))))



############ Con nueva base de datos variable continua normalizada

datos_me$experiment<-ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="asentamientos",1,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="base",2,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="increm_cutza",3,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="mejora_efi",4,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="reduc_agua",5,ifelse(datos_me$budget==50&datos_me$budget_split=="action_budget"&datos_me$stress=="reduc_cutza",6,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="asentamientos",7,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="base",8,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="increm_cutza",9,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="mejora_efi",10,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="reduc_agua",11,ifelse(datos_me$budget==1000&datos_me$budget_split=="action_budget"&datos_me$stress=="reduc_cutza",12,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="asentamientos",13,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="base",14,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="increm_cutza",15,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="mejora_efi",16,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="reduc_agua",17,ifelse(datos_me$budget==2000&datos_me$budget_split=="action_budget"&datos_me$stress=="reduc_cutza",18,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="asentamientos",19,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="base",20,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="increm_cutza",21,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="mejora_efi",22,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="reduc_agua",23,ifelse(datos_me$budget==50&datos_me$budget_split=="system_budget"&datos_me$stress=="reduc_cutza",24,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="asentamientos",25,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="base",26,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="increm_cutza",27,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="mejora_efi",28,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="reduc_agua",29,ifelse(datos_me$budget==1000&datos_me$budget_split=="system_budget"&datos_me$stress=="reduc_cutza",30,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="asentamientos",31,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="base",32,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="increm_cutza",33,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="mejora_efi",34,ifelse(datos_me$budget==2000&datos_me$budget_split=="system_budget"&datos_me$stress=="reduc_agua",35,36)))))))))))))))))))))))))))))))))))
```

```{r}
datos_mes<-as.data.frame(tapply(datos_me$flooding_vulnerability_n, datos_me$experiment, mean))
colnames(datos_mes)<-"vulnerabilidad"
library(cluster)
library(purrr)
datos_mes <- scale(datos_mes)
hc4 <- diana(datos_mes) ## Computo de agrupamientos jerárquicos divisivos
hc4$dc ##Coeficiente de división
pltree(hc4, cex = 0.6, hang = -1, main = "Dendrogram of diana") ###Dendograma( cada grupo está vinculado a dos o más grupos sucesores)###
clust <- cutree(hc4, k = 9)###Cortar el arbol en 5 grupos
library(factoextra)
library(ggplot2)
pltree(hc4, hang=-1, cex = 0.6,main="Clasificación de experimentos",xlab="experimentos")
rect.hclust(hc4, k = 5, border = 2:10)

####Inundaciones
datos_mes<-as.data.frame(tapply(datos_me$flooding_vulnerability_n, datos_me$experiment, mean))
colnames(datos_mes)<-"vulnerabilidad"
library(cluster)
library(purrr)
datos_mes <- scale(datos_mes)
hc4 <- diana(datos_mes) ## Computo de agrupamientos jerárquicos divisivos
hc4$dc ##Coeficiente de división
pltree(hc4, cex = 0.6, hang = -1, main = "Dendrogram of diana") ###Dendograma( cada grupo está vinculado a dos o más grupos sucesores)###
clust <- cutree(hc4, k = 9)###Cortar el arbol en 5 grupos
library(factoextra)
library(ggplot2)
pltree(hc4, hang=-1, cex = 0.6,main="Clasificación de experimentos",xlab="experimentos")
rect.hclust(hc4, k = 5, border = 2:10)


```

```{r clusters, eval=TRUE}
datos_me$experiment <- as.factor(datos_me$experiment)
datos_me$cluster <- ifelse(datos_me$experiment=="1"|datos_me$experiment=="16"|datos_me$experiment=="8"|datos_me$experiment=="24"|datos_me$experiment=="9"|datos_me$experiment=="3"|datos_me$experiment=="18"|datos_me$experiment=="4"|datos_me$experiment=="19","cluster_1",ifelse(datos_me$experiment=="6"|datos_me$experiment=="13"|datos_me$experiment=="29"|datos_me$experiment=="21"|datos_me$experiment=="28"|datos_me$experiment=="14"|datos_me$experiment=="23"|datos_me$experiment=="11"|datos_me$experiment=="26","cluster_2", ifelse(datos_me$experiment=="2"|datos_me$experiment=="17"|datos_me$experiment=="10"|datos_me$experiment=="5"|datos_me$experiment=="20","cluster_3",ifelse(datos_me$experiment=="7"|datos_me$experiment=="15"|datos_me$experiment=="22"|datos_me$experiment=="30"|datos_me$experiment=="25","cluster_4","cluster_5"))))                                                                                   
datos_me$cluster<- as.factor( datos_me$cluster)  

levels(datos_me$cluster)

myColors <- ifelse(levels(datos_me$cluster)=="cluster_1" , "red", 
              ifelse(levels(datos_me$cluster)=="cluster_2", "green",ifelse(levels(datos_me$cluster)=="cluster_3", "blue",ifelse(levels(datos_me$cluster)=="cluster_4", "cyan","pink")) ) )

boxplot(datos_me$scarcity_vulnerability~datos_me$cluster,col=myColors,ylab = "vulnerabilidad",xlab = "clusters")

aov.1<-aov(datos_me$scarcity_vulnerability ~ datos_me$cluster)
summary(aov.1)
TukeyHSD(aov.1, conf.level=.95)
plot(TukeyHSD(aov(datos_me$scarcity_vulnerability ~ datos_me$cluster), conf.level=.95))




#####Con nueva BD variable normalizada continua

##Escasez
datos_me$experiment <- as.factor(datos_me$experiment)
datos_me$cluster <- ifelse(datos_me$experiment=="1"|datos_me$experiment=="19"|datos_me$experiment=="3"|datos_me$experiment=="21"|datos_me$experiment=="8"|datos_me$experiment=="30"|datos_me$experiment=="26"|datos_me$experiment=="12"|datos_me$experiment=="32"|datos_me$experiment=="36"|datos_me$experiment=="25"|datos_me$experiment=="4"|datos_me$experiment=="22"|datos_me$experiment=="7"|datos_me$experiment=="14"|datos_me$experiment=="18"|datos_me$experiment=="31"|datos_me$experiment=="9"|datos_me$experiment=="33"|datos_me$experiment=="27","cluster_1",ifelse(datos_me$experiment=="10"|datos_me$experiment=="28"|datos_me$experiment=="16"|datos_me$experiment=="34"|datos_me$experiment=="13"|datos_me$experiment=="15","cluster_2", ifelse(datos_me$experiment=="2"|datos_me$experiment=="20"|datos_me$experiment=="6"|datos_me$experiment=="24"|datos_me$experiment=="17","cluster_3",ifelse(datos_me$experiment=="5"|datos_me$experiment=="23","cluster_4","cluster_5"))))                                                                                   
datos_me$cluster<- as.factor( datos_me$cluster)  

levels(datos_me$cluster)

myColors <- ifelse(levels(datos_me$cluster)=="cluster_1" , "red", 
              ifelse(levels(datos_me$cluster)=="cluster_2", "green",ifelse(levels(datos_me$cluster)=="cluster_3", "blue",ifelse(levels(datos_me$cluster)=="cluster_4", "cyan","pink")) ) )

boxplot(datos_me$scarcity_vulnerability_n~datos_me$cluster,col=myColors,ylab = "vulnerabilidad a escasez",xlab = "clusters")

aov.1<-aov(datos_me$scarcity_vulnerability_n ~ datos_me$cluster)
summary(aov.1)
TukeyHSD(aov.1, conf.level=.95)
plot(TukeyHSD(aov(datos_me$scarcity_vulnerability_n ~ datos_me$cluster), conf.level=.95))





##Inundaciones
datos_me$experiment <- as.factor(datos_me$experiment)
datos_me$cluster <- ifelse(datos_me$experiment=="1"|datos_me$experiment=="4"|datos_me$experiment=="5"|datos_me$experiment=="20"|datos_me$experiment=="2"|datos_me$experiment=="23"|datos_me$experiment=="3"|datos_me$experiment=="24"|datos_me$experiment=="21"|datos_me$experiment=="6"|datos_me$experiment=="19"|datos_me$experiment=="22","cluster_1",ifelse(datos_me$experiment=="7"|datos_me$experiment=="8"|datos_me$experiment=="25"|datos_me$experiment=="10"|datos_me$experiment=="26"|datos_me$experiment=="9"|datos_me$experiment=="27"|datos_me$experiment=="12"|datos_me$experiment=="11"|datos_me$experiment=="28"|datos_me$experiment=="30","cluster_2", ifelse(datos_me$experiment=="29","cluster_3",ifelse(datos_me$experiment=="13"|datos_me$experiment=="16"|datos_me$experiment=="14"|datos_me$experiment=="17"|datos_me$experiment=="18"|datos_me$experiment=="35"|datos_me$experiment=="15"|datos_me$experiment=="31"|datos_me$experiment=="32"|datos_me$experiment=="33","cluster_4","cluster_5"))))                                                                                   
datos_me$cluster<- as.factor( datos_me$cluster)  

levels(datos_me$cluster)

myColors <- ifelse(levels(datos_me$cluster)=="cluster_1" , "red", 
              ifelse(levels(datos_me$cluster)=="cluster_2", "green",ifelse(levels(datos_me$cluster)=="cluster_3", "blue",ifelse(levels(datos_me$cluster)=="cluster_4", "cyan","pink")) ) )

boxplot(datos_me$flooding_vulnerability_n~datos_me$cluster,col=myColors,ylab = "vulnerabilidad a inundaciones",xlab = "clusters")

aov.1<-aov(datos_me$flooding_vulnerability_n ~ datos_me$cluster)
summary(aov.1)
TukeyHSD(aov.1, conf.level=.95)
plot(TukeyHSD(aov(datos_me$flooding_vulnerability_n ~ datos_me$cluster), conf.level=.95))
```

```{r}

library(DMwR2)

datos_ss<-read.csv("stressing_scenarios_equidista.csv",header = T)

bdarbol<-subset(datos_ss, year==2060)
str(bdarbol)
set.seed(1234)
vul <- sample(2, nrow(bdarbol), replace=TRUE, prob=c(0.7, 0.3))
trainData <- bdarbol[vul==1,]
testData <- bdarbol[vul==2,]
library(party)
myFormula <- scarcity_vulnerability ~ budget + budget_split +
stress 
vul_ctree <- ctree(myFormula, data=trainData)
# check the prediction
table(predict(vul_ctree), trainData$scarcity_vulnerability)
print(vul_ctree)
plot(vul_ctree)
plot(vul_ctree, type="simple")


```

